version: '3'
services:
  node-app:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    image: hoangquang153636/custom_nodeapp:1.0

  mongo:
    image: mongo:8.0
    ports:
      - "27017:27017"
